### ISSUE TITLE
Can't install this module on Alfresco Community v5.1.g, v5.1.f, v5.2

### ISSUE THREAD

**Issue by Zholaman** [IntesysOpenway/openway-tasklist#1]
Hi,

I have tried to install your module (version 5.1.6.1.7 and 5.1.6.1.2) on  fresh installed of Alfresco Community v.**5.1.g**, v.**5.1.f**, v.**5.2** but no success. 

I used the following steps:
1. java -jar bin/alfresco-mmt.jar install amps/openway-tasklist-share-5.1.6.1.7.amp tomcat/webapps/share.war
2. Check: http://localhost:8080/share/page/modules/deploy
3. If not listed I will have deleted it: java -jar bin/alfresco-mmt.jar uninstall openway-tasklist-share tomcat/webapps/share.war
4. java -jar bin/alfresco-mmt.jar install amps/openway-tasklist-share-5.1.6.1.7.amp tomcat/webapps/alfresco.war
5. Check: http://localhost:8080/share/page/modules/deploy

I tried to install (both version 5.1.6.1.7 and 5.1.6.1.2) into share.was and alfresco.war on Alfresco Community v.**5.1.g**, v.**5.1.f**, v.**5.2** but no success.

Thanks I hope you help us.

Best regards,
Zholaman

**Comment by RuudGianesini** [comment]
Hi Zholaman,
The module is tested on 5.1.g Community Edition, not on 5.2.
I tried to repeat the installation but I've no errors. Try follow this steps:
1. Install the 2 amps:
	- java -jar bin/alfresco-mmt.jar install amps/openway-tasklist-alfresco-5.1.6.1.7.amp tomcat/webapps/alfresco.war
	- java -jar bin/alfresco-mmt.jar install amps_share/openway-tasklist-share-5.1.6.1.7.amp tomcat/webapps/share.war
2. Check if the module has been installed, using this command:
	- java -jar bin/alfresco-mmt.jar list ./tomcat/webapps/alfresco.war
	- java -jar bin/alfresco-mmt.jar list ./tomcat/webapps/share.war
3. Run Alfresco and check on logs if you find some rows like this:
>  ...
>  [repo.module.ModuleServiceImpl] [localhost-startStop-1] Starting module 'openway-tasklist-alfresco'
>  ...
>  [config.packaging.ModulePackageManager] [localhost-startStop-1] Intesys Openway Tasklist - Share

4. Check http://localhost:8080/share/page/modules/deploy. You should find a module called openway-tasklist-extension
5. Go on page My Tasks and check if the page is changed

Best regards,
Ruud

**Comment by Zholaman** [comment]
Hi, I am sorry for late answer.

I will try to deploy as you advice.

Thank you very much!
